-- GENERATED by C->Haskell Compiler, version 0.16.3 Crystal Seed, 24 Jan 2009 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "OfxProperty.chs" #-}{-# LANGUAGE ForeignFunctionInterface, DeriveDataTypeable, TypeSynonymInstances  #-}

module OfxProperty where

import C2HS
import C2HS
import System.IO.Unsafe
import Foreign
import Foreign.C
import Foreign.C.String
import Foreign.Storable
import Foreign.Ptr
import Control.Monad
import Control.Applicative
import Data.Typeable

-- | TODO : find a way to automagically pass all defines 
kOfxPropertySuite = "OfxPropertySuite" 

-- |Blind pointer on a property set handle
type OfxPropertySetHandle = Ptr ()

-- |Bindings to a property suite.
-- |A property suite contains lots of functions used to retrieve and set properties
-- |to OFX objects.
data HOfxPropertySuiteV1 = 
  HOfxPropertySuiteV1 
    {
        propSetPointer :: FunPtr (OfxPropertySetHandle 
                       -> CString
                       -> CInt
                       -> Ptr ()
                       -> IO CInt)

    }


instance Storable HOfxPropertySuiteV1 where
    sizeOf _ = 144
{-# LINE 40 "OfxProperty.chs" #-}
    alignment _ = 4
    peek p = 
      HOfxPropertySuiteV1
        <$> (\ptr -> do {peekByteOff ptr 0 ::IO (FunPtr ((Ptr ()) -> ((Ptr CChar) -> (CInt -> ((Ptr ()) -> (IO CInt))))))}) p
    
    poke p x = do
      (\ptr val -> do {pokeByteOff ptr 0 (val::(FunPtr ((Ptr ()) -> ((Ptr CChar) -> (CInt -> ((Ptr ()) -> (IO CInt)))))))}) p (propSetPointer x)

